### ISSUE TITLE
Create Environment Setup Documentation

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#1]
### Proposed work
This project uses many different software tools and libraries that need to be installed. Add documentation to the README on how to install and set up these environments.
### Task list
- [x] Add documentation for setting up VSCode, Platform.io, and Teensyduino
- [x] Add documentation for setting up KiCad
- [x] Add documentation for setting up Fusion 360
