### ISSUE TITLE
Determine Unit Test Framework and Hardware Simulation Support

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#12]
### Proposed work
Platform.io offers an integrated unit testing framework. Learn more about and figure out what needs to be done to integrate with it. There are also hardware simulators that can be interfaced with the unit testing framework. Research them and set up a hardware simulator for the project's hardware configuration.
### Task list
- [x] Investigate Platform.io unit testing
- [x] Investigate hardware simulators
- [x] Choose and setup a hardware simulator to be used with the project

**Comment by tfranks31** [comment]
PlatformIO integrates Unity testing, which will be the test framework used. Full MC/DC coverage will be aimed at when writing tests, but no formal testing tool will be used to measure coverage. Further investigation also prompted the decision to develop our own simulated hardware. A new hardware interface layer will need to be introduced so that tests can use the simulated hardware modules instead of physical hardware modules. Also, we will begin to profile each function/method within the codebase. A mark of how long each function/method takes will be added as a comment to the header. These profiles will be re-run each time a function/method is created or updated, as well as any functions/methods that rely on it. These will be profiled with actual hardware attached to obtain actual performance.
