### ISSUE TITLE
Re-do Breakout Board Symbols and Simplify the Schematic

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#13]
### Proposed work
The EPC901 symbol was created quickly and does not complement the breakout board schematic. Change the symbol to complement it and help de-clutter the schematic.
### Task list
- [x] Redesign EPC901 symbol
- [x] Redesign ADC symbol
- [x] Retrace for simplicity
