### ISSUE TITLE
Test All Received Components

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#14]
### Proposed work
All electrical components have arrived and need to be tested for proper behavior. Take each component, assemble it if necessary, and verify that the hardware works as expected.

### Task list
- [x] Assemble Teensy Pins
- [x] Test Teensy
- [x] Test Laser Diode
- [x] Test Diffraction Grating
- [x] Test Display Cable and connector
- [x] Test TFT Display
- [x] Test Battery Holder with Snap
- [x] Test DC converter
- [x] Test Joystick
- [x] Test LED
- [x] Test button
- [x] Test LLC
