### ISSUE TITLE
Create Footprints for Breakout Board

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#16]
### Proposed work
Footprints need to be created for all of the PCB components. Create them!
### Task list
- [x] Create footprint for the header pins connector
- [x] Create footprint for the ADC
- [x] Create footprint for the CCD
- [x] Create footprints for all minor parts
