### ISSUE TITLE
Create Footprints for main PCB

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#17]
### Proposed work
Footprints need to be created for all of the PCB components. Create them!
### Task list
- [x] Create footprint for battery connection
- [x] Create footprint for power switch
- [x] Create footprint for DC converter
- [x] Create footprint for LLC
- [x] Create footprint for LD connection
- [x] Create footprint for status LED
- [x] Create footprint for joystick module
- [x] Create footprint for breakout board connection
- [x] Create footprint for TFT connection
- [x] Create footprint for Teensy connection
- [x] Create footprint for all minor parts
