### ISSUE TITLE
Create Component Module Libraries

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#21]
### Proposed work
Each of the hardware components should have a library available for us to interact with and build upon. Create them.
### Task list
- [ ] Create EPC901 module library
- [ ] Create Joystick module library
- [ ] Create LED module library
