### ISSUE TITLE
Continue Working on Use Cases

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#22]
### Proposed work
Continue working on those use cases! A list of all needed ones is here. New requirements should be updated here as seen fit.
### Task list
- [ ] Lets user know what it is doing even if display is off (status)
- [ ] Can sleep
- [ ] Can wakeup
- [ ] Can change laser intensity setting
- [ ] Can manually enable laser and CCD dectector
- [ ] Can manually disable CCD dectector
- [ ] Can tell if ccd isn't working
- [ ] Can tell the user how to use the system
- [ ] Can run a maintenance check on all hardware
- [ ] Can profile hardware
- [ ] Can perform different types of scans (duration, periodic, endless, varying intensities)
- [ ] Can display real time results
- [ ] Can store results and playback results
- [ ] Can compare scan results
- [ ] Can display molecular structures of scan results
- [ ] Can display raw signal
- [ ] Can display raman spectrum
- [ ] Can display cleaned signal
- [ ] Can display material composition
