### ISSUE TITLE
Source Battery and Voltage Conversion Needs

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#3]
### Proposed work
A battery and some kind of voltage conversion still need to be sourced. Worst case scenario, the instrument will draw 200mAh max. Under normal operation (scanning and viewing display), it will likely draw 100mAh max. The maximum voltage needed for operation is 5V.

Preferably, find a power source that is either rechargeable or can be easily replaced (ex. multiple AAs).
### Task list
- [x] Investigate rechargeable power source options
- [x] Investigate battery packs that allow for common battery replacement
- [x] If needed, investigate methods of controlling the battery output voltage
- [x] Make a decision and order
