### ISSUE TITLE
Optimize PCBs

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#31]
### Proposed work
The first rev of the PCBs is complete! However, there are many things that can likely be changed and improved upon. Look at the tasks below for how to improve upon them.
### Task list
- [x] Move parts closer
- [x] Make edges tighter
- [x] Reroute for best paths
- [x] Better separate digital and analog planes of the PCB
- [x] Minimize as much as reasonably possible
- [x] Remove unnecessary laser resistor
- [x] Remove unnecessary backlight resistor
- [x] Enlarge header pin size on breakout board
- [x] #43 
- [x] Enlarge lens holes
- [x] Enlarge and plate mounting holes
