### ISSUE TITLE
Determine Software Architecture

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#4]
### Proposed work
Decide how the software will be organized and how the system will fit together. Write design documents and add them to the Wiki.
### Task list
- [x] Investigate how Teenydunio architecture is typically set up
- [x] Break up and create layers of abstraction for much of the hardware interaction and general processing
- [x] Investigate unit testing for microcontrollers

**Comment by tfranks31** [comment]
Styles have been determined. Modules will be used and will be grouped/organized based on their level of interaction with the system.
