### ISSUE TITLE
Solder PCBs

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#44]
### Proposed work
Solder the PCBs!
### Task list
- [x] Solder the breakout board components
- [x] Solder the main board components
- [x] Set up the test setup
