### ISSUE TITLE
Source and Implement EEPROM

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#48]
### Proposed work
We need an EEPROM on the device to store captured spectra. Look for one, primarily one that can communicate over I2C, and integrate it into the PCB.
### Task list
- [x] Source EEPROM
- [x] Create EEPROM symbol
- [x] Add EEPROM to schematic
- [x] Create EEPROM footprint
- [x] Add EEPROM to PCB
