### ISSUE TITLE
Source and Implement Terminal Blocks

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#49]
### Proposed work
After some concerns with wire tension, ripping PCB pads off, and potentially faulty components, it was decided that some sort of connector should be added. However, due to my lack of understanding of crimping, choosing, and assembling connectors, it was decided that terminal blocks would be the easiest way to reduce wire tension and allow for replaceable components. Find PCB terminal blocks for the laser module and the battery connector.
### Task list
- [x] Source terminal blocks
- [x] Create terminal block symbol
- [x] Add terminal blocks to schematic
- [x] Create terminal block footprint
- [x] Add terminal block to PCB
