### ISSUE TITLE
Create Empty Software Design Structure

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#5]
### Proposed work
Add the empty structure for the software design. This includes adding the empty main file, creating new directories, adding any 3rd party libraries, and testing that the software will compile correctly.
### Task list
- [x] Create new directories
- [x] Add main
- [x] Add any 3rd party libraries needed
### Testing
- [x] Test that the software will compile correctly
