### ISSUE TITLE
Model and Print First Version of the Encasing

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#50]
### Proposed work
Time to model the case! Model the first version.
### Task list
- [x] Model Handle
- [x] Model PCB Housing
- [x] Compute angle for diffraction grating and lenses
- [x] Model optics housing
- [x] Make assemblable
- [x] Model different heads
- [x] Modify until properly fitted
