### ISSUE TITLE
Make models for all non-case hardware

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#51]
### Proposed work
While designing the case, I discovered how much of a pain it is to measure physical models and use those measurements to determine placement. It would be much easier if I had models of each external hardware piece for easier visualization and placement checks.
### Task list
- [ ] Create populated PCB model
- [ ] Create TFT model
- [ ] Create Diffraction Grating model
- [ ] Create ribbon cable model
- [ ] Create Battery holder, snap, and battery models
- [ ] Create Laser model
