### ISSUE TITLE
Create MemoryManager class

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#56]
### Proposed work
Create a class that has the sole purpose of structuring, converting, and writing memory to and from the EEPROMs.
### Task list
- [x] Design memory structure for HRS
- [ ] Create a structure for the designed memory structure
- [ ] Create methods that convert the raw EEPROM pages into the memory structure
- [ ] Create methods for writing different data to the EEPROM pages
