### ISSUE TITLE
Create PinConfig Constants File

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#58]
### Proposed work
For some reason, I thought it would be a good idea to let the pin numbers be passed into the constructors for all of the modules. I believe it was because I wanted to manage all the pin numbers in one spot in the code. Well... it is very easy to do that through a constants file that contains the pin configuration _and_ it allows us to use faster digital writing and reading.

Remove the pin number parameters from the module constructors and create the constants file that contains the pin configuration for the instrument.
### Task list
- [x] Remove the pin number parameters
- [x] Create the constants file
- [x] Make all pin configurations use the constants file
