### ISSUE TITLE
Design PCBs

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#7]
### Proposed work
Create the initial PCB designs to be used for this project. Create the schematics for all components and convert them to PCB layouts. Two PCBs need to be made. One main PCB for the majority of the system, and another breakout board for the CCD detector and ADC.
### Task list
- [x] #8
- [x] #16 
- [x] Determine layout for breakout board
- [x] Lay traces for breakout board
- [x] #9
- [x] #17 
- [x] Determine layout for main PCB
- [x] Lay traces for main PCB
