### ISSUE TITLE
Create Scan Processing Class

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#72]
### Proposed work
We need to do much processing with the scanned in data from the CCD. This involves scaling the ADC readings, Denoising the signal with baseline correction, and providing means of comparison between scans. All of these should be placed under a scan processing class.
### Task list
- [ ] Create ADC scaler
- [ ] Create Denoise and Baseline correction algorithm using wavelet transforms
- [ ] Create scan comparison algorithm
