### ISSUE TITLE
Create Scan Conducting Class

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#73]
### Proposed work
We need a class that handles all high-level aspects of scanning and acts as an endpoint for interacting with everything scans. This will include the act of scanning, comparing scans with pre-existing scans, scans to and from memory, and scan settings configuration.
### Task list
- [ ] Perform, clean, and store scans
- [ ] Compare scans with other scans stored in memory
- [ ] Manage scan memory (CRUD)
- [ ] Scan settings configuration
