### ISSUE TITLE
Create Breakout Board Schematics

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#8]
### Proposed work
Create all of the breakout board schematics. This involves creating schematics for the CCD, ADC, connectors out to the main PCB, and any resistors, capacitors, and/or diodes needed. 
### Task list
- [x] Create CCD schematic
- [x] Create ADC schematic
- [x] Create board connector schematic
- [x] Connect schematics as needed
