### ISSUE TITLE
Create Main PCB Schematics

### ISSUE THREAD

**Issue by tfranks31** [tfranks31/Budget-Handheld-Raman-Spectrometer#9]
### Proposed work
Create the main PCB schematic. This involves connection points for the laser, Display, joystick, and breakout board. This also involves creating the connection points for the Teensy and room for the battery module and potential voltage regulator module. Add any resistors, capacitors, or diodes as necessary.
### Task list
- [x] Create Laser schematic
- [x] Create Display connector schematic
- [x] Create Joystick connector schematic
- [x] Create breakout board connector schematic
- [x] Create Teensy connector schematic
- [x] Create power schematic
- [x] Create status LED and button schematics
- [x] Connect schematics as needed
